### ISSUE TITLE
如何写一份样式指南

### ISSUE THREAD

**Issue by zhouwenbin** [zhouwenbin/blog#5]
写样式的时候，一开始都会比较清晰，要找东西都比较好找。随着时间的推移，项目越来越大，记忆越来越模糊，要找东西就会变得特别麻烦。所以要编写一份类似boostrap那样的文档，要找结构和样式都比较好找。

如何写样式指南，我使用了[postcss-style-guide](https://github.com/morishitter/postcss-style-guide)，用法很简单。
## 安装

首先安装node,npm,gulp
然后在命令行输入

```
npm install postcss postcss-style-guide highlight.js
```

修改`gulpfile.js`文件

``` js
var fs = require('fs');
var gulp = require('gulp');
var postcss = require('gulp-postcss');
gulp.task('guild', function () {
    var processedCSS = fs.readFileSync('./app/static/css/pages/common/common.css', 'utf-8');
    return gulp.src('./app/static/css/pages/common/common.css')
        .pipe(postcss([
            require('postcss-style-guide')({
                name: "样式指南",
                processedCSS: processedCSS
            })
        ]))
        .pipe(gulp.dest('./docs'));
});
```

然后在需要生成的样式文件输入下面的注释

``` css
/*
@styleguide

# I love Twitter Bootstrap

Use the button classes on an `<a>`, `<button>`, `<input>` element.

<button class="btn">Button</button>

    <button class="btn">Button</button>

*/
.btn {
  display: inline-block;
  padding: 6px 12px;
  margin-bottom: 0;
  font-size: 14px;
  font-weight: normal;
  line-height: 1.42857143;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  touch-action: manipulation;
  cursor: pointer;
  user-select: none;
  background-image: none;
  border: 1px solid transparent;
  border-radius: 4px;
}

.btn:hover,
.btn:focus,
.btn.focus {
  color: #333;
  text-decoration: none;
}
```

在命令行输入`gulp guild`，工具会帮我们生成下面的界面。可以预览组件，查看`html`，`css`代码。
![image](https://cloud.githubusercontent.com/assets/1428546/11296778/27e5cbf6-8faf-11e5-8f79-ffacc170d40a.png)

结构写在样式的注释里，也能帮我们后面各快的回忆结构的用法。
